spring:
  datasource:
    url: "jdbc:postgresql://ep-dry-scene-adi0iacg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
    username: "neondb_owner"
    password: "npg_zED7g2ofTsAc"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false

server:
  port: 8080