########################################
# Banco de Dados H2
########################################
spring.datasource.url=jdbc:h2:mem:bitstudent-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Executar SEMPRE o data.sql depois da criação das tabelas
spring.sql.init.mode=always

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

########################################
# Configuração Server
########################################
server.port=8080

# Impedir carregamento automático R2DBC (evita erro)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

########################################
# Gmail OAuth2 (usado apenas para leitura via API)
########################################
gmail.credentials.path=gmail/credentials.json
gmail.application.name=bitStudent

########################################
# SMTP - Envio de email (ESSENCIAL)
########################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreplybitstudent@gmail.com
spring.mail.password=ubozusdhulgsdnsv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000